#
# Joshua Henderson, joshua.henderson@microchip.com
# Copyright (C) 2014 Microchip Technology, Inc.  All rights reserved.
#
obj-y = reset.o irq.o \
	pbtimer.o \
	ocmp.o

obj-$(CONFIG_RFKILL)           += pic32-bluetooth-csr8811.o
