#
# Joshua Henderson, joshua.henderson@microchip.com
# Copyright (C) 2014 Microchip Technology, Inc.  All rights reserved.
#
obj-y			:= init.o setup.o time.o \
				early_pinctrl.o

obj-$(CONFIG_EARLY_PRINTK)	+= early_console.o


