#
# PIC32 Platform Support
#
snd-soc-pic32-i2s-objs := pic32-i2s.o

obj-$(CONFIG_SND_PIC32_SOC_I2S) += snd-soc-pic32-i2s.o

# PIC32 Machine Support
snd-soc-pic32-proto-objs := pic32-proto.o

obj-$(CONFIG_SND_PIC32_SOC_CODEC_PROTO) += snd-soc-pic32-proto.o
